/** Cozy "Family Hearth" design tokens, mirrored from the Stitch design system. */
/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{vue,ts}'],
  theme: {
    extend: {
      colors: {
        background: '#fcf9f3',
        surface: '#fcf9f3',
        'surface-bright': '#fcf9f3',
        'surface-dim': '#dcdad4',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f6f3ed',
        'surface-container': '#f0eee8',
        'surface-container-high': '#ebe8e2',
        'surface-container-highest': '#e5e2dc',
        'surface-variant': '#e5e2dc',
        'on-surface': '#1c1c18',
        'on-surface-variant': '#424844',
        'on-background': '#1c1c18',
        outline: '#727973',
        'outline-variant': '#c2c8c2',
        primary: '#4c6455',
        'on-primary': '#ffffff',
        'primary-container': '#8fa998',
        'on-primary-container': '#273e31',
        'primary-fixed': '#cee9d6',
        secondary: '#7b5455',
        'on-secondary': '#ffffff',
        'secondary-container': '#fdcbcb',
        'on-secondary-container': '#795354',
        tertiary: '#645a6f',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#aa9eb5',
        'on-tertiary-container': '#3e3548',
        'tertiary-fixed': '#ebdef6',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'inverse-surface': '#31312d',
        'inverse-on-surface': '#f3f0ea',
      },
      borderRadius: {
        DEFAULT: '0.5rem',
        sm: '0.25rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.5rem',
        full: '9999px',
      },
      spacing: {
        base: '8px',
        'stack-sm': '12px',
        'stack-md': '24px',
        'stack-lg': '48px',
        gutter: '24px',
        'container-padding-mobile': '16px',
        'container-padding-desktop': '32px',
      },
      fontFamily: {
        headline: ['"Plus Jakarta Sans"', 'sans-serif'],
        'headline-xl': ['"Plus Jakarta Sans"', 'sans-serif'],
        'headline-lg': ['"Plus Jakarta Sans"', 'sans-serif'],
        'label-md': ['"Plus Jakarta Sans"', 'sans-serif'],
        body: ['"Be Vietnam Pro"', 'sans-serif'],
        'body-md': ['"Be Vietnam Pro"', 'sans-serif'],
        'body-lg': ['"Be Vietnam Pro"', 'sans-serif'],
      },
      fontSize: {
        'headline-xl': ['40px', { lineHeight: '48px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.05em', fontWeight: '600' }],
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '500' }],
      },
      boxShadow: {
        card: '0px 4px 24px rgba(76, 100, 85, 0.08)',
        float: '0px 10px 30px rgba(76, 100, 85, 0.12)',
      },
    },
  },
  plugins: [],
};
